### ISSUE TITLE
Captcha при изпращане на протокол/сигнал

### ISSUE THREAD

**Issue by hkdobrev** [ti-broish/results#47]

**Comment by ogonommo** [comment]
You can use "react-google-recaptcha".

The request header holding the token should be named "x-recaptcha-token".

**Comment by dgeorgiev** [comment]
@ogonommo привет, инсталирах https://www.npmjs.com/package/react-google-recaptcha-v3 за да използваме последната версия понеже react-google-recaptcha` е малко остаряло, но при изпращане на формата си минава успешно без хедър или попълнен токен-а някъде - дали може малко информация относно https://github.com/ti-broish/api/pull/158 понеже доколкото прегледах би трябвало в момента да не сработва формата без captcha?

**Comment by hkdobrev** [comment]
@dgeorgiev Recaptcha проверката не е включена на staging все още. Можем да я включим като вече се праща token-а.
