### ISSUE TITLE
Рискови секции на картата

### ISSUE THREAD

**Issue by hkdobrev** [ti-broish/results#50]
- [x] В табовете над картата, таб "Секции"  да стане активен по подразбиране когато все още нямаме сигнали в API-то, а таб "Сигнали" да бъде неактивен. Тоест актвините табове ще се определят динамично на база за какво имаме данни 
- [x] таб "Секции" да показва както и досега броя секции в hover менюто, но също така да показва и броя средно рискови и високо рискови секции
- [x] областите да се оцветяват в жълто и оранжево спрямо това дали има такива секции вътре (може би и спрямо колко такива имат)
Когато се изброяват отдолу в списъка МИР-ове, общини и т.н., линията за броя секции (може би) да има два режима:
- [ ] един който ползва ResultsLine така че да показва 3 цвята - зелен,жълт, оранжев за нисък, среден и висок риск и така да се вижда къде има повече такива секции 
- [ ] друг, който да показва различна дължина на линията за броя секции в различните райони/общини/райони

Ако има по-добра идея тук нека да пробваме. До момента ние имаме само два вида линии в резултатите - или линия която е с един цвят и променлива дължина или линия, която е като stacked horizontal chart и винаги изпълва 100% от реда и е разделена на сегменти, но нямаме линия, която да е с променлива дължина и пак да е разделена на сегменти. Може би ще е полезно за рисковите секции.

- [x] когато се изброяват секциите в дадена община/град, може да се отбележат по някакъв с някакъв warning знак и информация на hover - "Секция със среден риск", "Секция със висок риск"
- [x] Когато се отвори страницата на конкретна секция да се покаже също тази информация в поле "Риск: "

**Comment by vladiangelov** [comment]
Requirements:

- [ ] В табовете над картата, таб "Секции"  да стане активен по подразбиране когато все още нямаме сигнали в API-то, а таб "Сигнали" да бъде неактивен. Тоест актвините табове ще се определят динамично на база за какво имаме данни 
- [ ] таб "Секции" да показва както и досега броя секции в hover менюто, но също така да показва и броя средно рискови и високо рискови секции
- [ ] областите да се оцветяват в жълто и оранжево спрямо това дали има такива секции вътре (може би и спрямо колко такива имат)
Когато се изброяват отдолу в списъка МИР-ове, общини и т.н., линията за броя секции (може би) да има два режима:
- [ ] един който ползва ResultsLine така че да показва 3 цвята - зелен,жълт, оранжев за нисък, среден и висок риск и така да се вижда къде има повече такива секции 
- [ ] друг, който да показва различна дължина на линията за броя секции в различните райони/общини/райони

Ако има по-добра идея тук нека да пробваме. До момента ние имаме само два вида линии в резултатите - или линия която е с един цвят и променлива дължина или линия, която е като stacked horizontal chart и винаги изпълва 100% от реда и е разделена на сегменти, но нямаме линия, която да е с променлива дължина и пак да е разделена на сегменти. Може би ще е полезно за рисковите секции.

- [ ] когато се изброяват секциите в дадена община/град, може да се отбележат по някакъв с някакъв warning знак и информация на hover - "Секция със среден риск", "Секция със висок риск"
- [ ] Когато се отвори страницата на конкретна секция да се покаже също тази информация в поле "Риск: "
